import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {useEffect, useState} from 'react'

const inter = Inter({ subsets: ['latin'] })

type Character = {
  name: string,
  image: string
}

export default function Home() {

  const [characters, setCharacters] = useState<Character>();

  useEffect(() => {
    fetch('https://rickandmortyapi.com/api/character')
      .then(response => response.json())
      .then(data =>{ 
        setCharacters(data.results[1])
          console.log(data.results[1]);
      });
}, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
          <h1>Hola soy {characters?.name} </h1>
          <img src={characters?.image} alt={characters?.name}/>
       
      </main>
    </>
  )
}
